### ISSUE TITLE
gapps missing

### ISSUE THREAD

**Issue by berndhofer** [supechicken/waydroid-androidtv-build#10] opened 2024-10-12 06:02 UTC
Hi there. The image itself is running great, but I am unable to initialize your custom gapps. I created the system subfolder etc. but no success. Also the google play cert leads to an error:

id.gsf/databases/gservices.db "select * from main where name = \"android_id\";"                    <
Error: unable to open database "/data/data/com.google.android.gsf/databases/gservices.db": unable to open database file

**Comment by supechicken** [comment] 2024-10-12 07:25
Boot the container once and try again?

**Comment by viell-dev** [comment] 2024-11-28 07:39
Try running `sudo waydroid init -f` again. That worked for me.

**Comment by supechicken** [comment] 2024-12-15 12:48
Closing as unable to reproduce.

**Closed** 2024-12-15 12:47 UTC
